package com.apache.sfdc.router.dto;

import lombok.Data;

@Data 
public class Account {
    private String Id;
    private Boolean IsDeleted;
    private String MasterRecordId;
    private String Name;
    private String Type;
    private String ParentId;
    private String BillingStreet;
    private String BillingCity;
    private String BillingState;
    private String BillingPostalCode;
    private String BillingCountry;
    private Double BillingLatitude;
    private Double BillingLongitude;
    private String BillingGeocodeAccuracy;
    private String BillingAddress;
    private String ShippingStreet;
    private String ShippingCity;
    private String ShippingState;
    private String ShippingPostalCode;
    private String ShippingCountry;
    private Double ShippingLatitude;
    private Double ShippingLongitude;
    private String ShippingGeocodeAccuracy;
    private String ShippingAddress;
    private String Phone;
    private String Fax;
    private String AccountNumber;
    private String Website;
    private String PhotoUrl;
    private String Sic;
    private String Industry;
    private String AnnualRevenue;
    private Integer NumberOfEmployees;
    private String Ownership;
    private String TickerSymbol;
    private String Description;
    private String Rating;
    private String Site;
    private String OwnerId;
    private String CreatedDate;
    private String CreatedById;
    private String LastModifiedDate;
    private String LastModifiedById;
    private String SystemModstamp;
    private String LastActivityDate;
    private String LastViewedDate;
    private String LastReferencedDate;
    private String Jigsaw;
    private String JigsawCompanyId;
    private String CleanStatus;
    private String AccountSource;
    private String DunsNumber;
    private String Tradestyle;
    private String NaicsCode;
    private String NaicsDesc;
    private String YearStarted;
    private String SicDesc;
    private String DandbCompanyId;
    private String OperatingHoursId;
    private String CustomerPriority__c;
    private String SLA__c;
    private String Active__c;
    private Double NumberofLocations__c;
    private String UpsellOpportunity__c;
    private String SLASerialNumber__c;
    private String SLAExpirationDate__c;
}
