server:
    port: 3931

camel:
    component:
        salesforce:
            client-id: ${SALESFORCE_CLIENT_ID}
            client-secret: ${SALESFORCE_CLIENT_SECRET}
            login-url: ${SALESFORCE_LOGIN_URL}
            api-version: ${SALESFORCE_API_VERSION}
            instance-url: ${SALESFORCE_INSTANCE_URL}

spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
    data:
        redis:
            host: ${REDIS_URL}
            port: ${REDIS_PORT}
            password: ${REDIS_PASSWORD}

mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        mapUnderscoreToCamelCase: true