camel:
    component:
        salesforce:
            client-id: 3MVG9q4K8Dm94dAwF6D70zsfWDZO2vEz0CCf0bQtywOlbgdghIYL0JLpyG2HP5bvUkV5Lm1B.4bZE0z6pkVu3
            client-secret: A532570413C1AB3952E7CEDEBDBFF0735651F2F8011B093C8CE03A646FF9AD0A
            user-name: admin@ecologysyncmanagementco.kr.dev
            password: qwer1234!!NLIi077LCt55mBjVM5AJKyTH
            login-url: https://login.salesforce.com
            api-version: 61


